build:
  stage: build
  image: "docker:${DOCKER_VERSION}"
  tags:
    - gitlab-org-docker
  variables:
    # Normally BuildKit would set this for us, but as this does not use
    # BuildKit we'll just pass it through for it
    TARGETARCH: amd64
  services:
    - "docker:${DOCKER_VERSION}-dind"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --build-arg DOCKER_VERSION="$DOCKER_VERSION"
      --build-arg TARGETARCH="$TARGETARCH"
      --tag "$BUILD_IMAGE_NAME"
      --tag "$BUILD_IMAGE_NAME_LATEST"
      .
    - docker push "$BUILD_IMAGE_NAME"
    - docker push "$BUILD_IMAGE_NAME_LATEST"
